services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:80"
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=50M
      - PHP_POST_MAX_SIZE=100M
